config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :people

  resources :skills

  resources :groups

  resources :organizations

  resources :todos

  resources :comments
  
  root "organizations#home"
  
  post "/group_list" => "people#group_list"
  
  post "/skill_list" => "people#skill_list"
  
  post "/s_group_list" => "skills#s_group_list"

  get "/orgns" => "todos#orgns"

  get "/persn" => "todos#persn"

  get "/pple" => "todos#pple"

end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :name, presence: true
  validates_uniqueness_of :name, scope: :group_id
  validates :group_id, presence: true
  belongs_to :group
  belongs_to :user
  has_and_belongs_to_many :skills, dependent: :destroy
  has_many :todos, dependent: :destroy
  

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.where( :user_id =>current_user.id)
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    org=Organization.where( :user_id =>current_user.id)
    if org.nil?
    @groups=org.first.groups
    @skills=@groups.first.skills
    else
    @groups=Group.where( :user_id =>current_user.id)
    @skills=Skill.where( :user_id =>current_user.id)
    end
    
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
    @prn=@person
    @groups=@person.group.organization.groups.all
    @skills=@person.group.skills.all
  end
   
  def group_list
    @groups=Group.where(:organization_id => params[:orgid])
    render partial: "group_list"
  end
  
  def skill_list
    @skills=Skill.where(:group_id => params[:groupid])
    render partial: "skill_list"
  end  
  
  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)
    @person.user_id= current_user.id 
    respond_to do |format|
      if @person.save
        if params[:skillid]!=nil
        params[:skillid].each do |i| 
		  @person.skills << Skill.find_by_id(i)
		end
		end
        format.html { redirect_to @person }
        format.json { render :show, status: :created, location: @person }
      else
        org=Organization.where( :user_id =>current_user.id)
		if org.nil?
		@groups=org.first.groups
		@skills=@groups.first.skills
		else
		@groups=Group.where( :user_id =>current_user.id)
		@skills=Skill.where( :user_id =>current_user.id)
        end
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        @person.skills.delete_all
        if params[:skillid]!= nil
        params[:skillid].each do |i| 
		  @person.skills << Skill.find_by_id(i)
		end
		end
        format.html { redirect_to @person }
        format.json { render :show, status: :ok, location: @person }
      else
        @groups=@person.group.organization.groups.all
        @skills=@person.group.skills.all
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.skills.delete_all
   
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :qualification, :group_id)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for @person, :html => { :class => "form-horizontal person" } do |f| %>
  
  <div class="field">
    <%= label_tag :organization %><br>
    <% if !@prn.nil? %>
    <%= select_tag :orgid, options_from_collection_for_select(Organization.where( :user_id =>current_user.id), "id", "name", @prn.group.organization.id), :class => 'form-control' %>
    <% else %>
    <%= select_tag :orgid, options_from_collection_for_select(Organization.where( :user_id =>current_user.id), "id", "name"), :class => 'form-control' %>
    <% if !(Organization.where( :user_id =>current_user.id)).exists? %>
    <p style="color:red;"><%= "Please create organiztion" %></p>
    <% end %>
    <% end %>
    
  </div>
  <script>
  $(function(){
    $("#orgid").change(function(){
       var value=$(this).val();
       $.ajax({
        url: "/group_list?orgid="+value,
        type: "POST",
        success: function(data) {
        $("#group_list").html(data);
		value=$("#person_group_id").val();
		$.ajax({
        url: "/skill_list?groupid="+value,
        type: "POST",
        success: function(data) {
        $("#skill_list").html(data);
		}
        });
		}
        });
    });
  });
  </script>
  <div class="field">
    <%= f.label :group %><br>
    <div id="group_list">
    <%= f.collection_select :group_id, @groups, :id, :name, {}, {:class => 'form-control'} %></div>
    <% if !(Organization.where( :user_id =>current_user.id)).exists?||!(Group.where( :user_id =>current_user.id)).exists? %>
    <p style="color:red;"><%= "Please create Group" %></p>
    <% end %>
  </div>
  
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <% if @person.errors.any? %>
    <% @person.errors.full_messages.each do |message| %>
        <% if message=~ /Name.*/ %>
        <p style="color:red;"><%= message %></p>
        <% end %>
    <% end %>
    <% end %>
  </div>
  
  <div class="control-group">
    <%= f.label :qualification, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :qualification, :class => 'form-control' %>
    </div>
  </div>
  
  <div class="field">
    <%= label_tag :skills %><br>
    <div id="skill_list">
     <%= render partial: "skill_list" %>
  </div>
  </div>
  <br />
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            people_path, :class => 'btn btn-default' %>
<% end %>

app/views/people/_group_list.html.erb
<%= select_tag :person_group_id, options_from_collection_for_select(@groups, "id", "name"), :name => "person[group_id]", :class => 'form-control' %>

app/views/people/_skill_list.html.erb
<% if !@prn.nil? %>
<%= select_tag :skillid, options_from_collection_for_select(@skills, "id", "name", @prn.skills.map {|s| s.id}), multiple: true, :class => 'form-control' %>
<% else %>
<%= select_tag :skillid, options_from_collection_for_select(@skills, "id", "name"), multiple: true, :class => 'form-control' %>
<% end %>
<script>
  $(function(){
    $("#person_group_id").change(function(){
       var value=$(this).val();
       $.ajax({
        url: "/skill_list?groupid="+value,
        type: "POST",
        success: function(data) {
        $("#skill_list").html(data);
		}
        });
    });
  });
  </script>

app/views/people/edit.html.erb
<div style="width:30%;">
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/people/index.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="table-responsive">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Qualification</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>

<script>
$(function(){
  $(".btn1").css({'background':'#F8F8F8','box-shadow':'0px 0px 10px #d8d8d8','padding':'2px 4px','color':'#333'});$(".btn-danger").css({'color':'white'});
});
</script>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.name, person_path(person), :class => 'btn btn1', :onmouseover => "$(this).css({'background':'#F8F8F8','box-shadow':'0px 0px 10px #666666','padding':'2px 4px','color':'#333'});", :onmouseleave => "$(this).css({'box-shadow':'0px 0px 10px #d8d8d8'});" %></td>
        <td><%= person.qualification %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_person_path(person), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_path(person),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_person_path,
            :class => 'btn btn-primary' %>

app/views/people/new.html.erb
<div style="width:30%;">
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/people/show.html.erb
<div style="width:50%;">
<%- model_class = Person -%>
<div class="page-header">
<div style="position:relative;margin-left:15%;">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
</div>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @person.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:qualification) %>:</strong></dt>
  <dd><%= @person.qualification %></dd>
  <dt><strong>Belongs to:</strong></dt>
  <dd><b><%= "group :" %></b><%= "#{@person.group.name} (" %> <b><%= "ORG :" %> </b><%= "#{@person.group.organization.name})" %></dd>
  <dt><strong>Skills:</strong></dt>
  <dd><% @person.skills.each do |skill| %>
         <%= skill.name %><br />
      <% end %>
  </dd>
  <dt><strong>To-dos:</strong></dt>
  <dd><table>
  <% @person.todos.each do |todo| %>
  <tr><td><b><%= "task :" %></b><%= "#{todo.task}" %></td><td>&nbsp;&nbsp;&nbsp;</td><td><b><%= "description :" %> </b><%= "#{todo.description}" %></td></tr>
  <% end %></table>
  </dd>
</dl>

<div style="position:relative;margin-left:15%;">
<%= link_to t('.back', :default => t("helpers.links.back")),
              people_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_person_path(@person), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              person_path(@person),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
</div>