config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :people

  resources :skills

  resources :groups

  resources :organizations

  resources :todos

  resources :comments
  
  root "organizations#home"
  
  post "/group_list" => "people#group_list"
  
  post "/skill_list" => "people#skill_list"
  
  post "/s_group_list" => "skills#s_group_list"

  get "/orgns" => "todos#orgns"

  get "/persn" => "todos#persn"

  get "/pple" => "todos#pple"

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, presence: true
  validates_uniqueness_of :name, scope: :organization_id
  
  validates :organization_id, presence: true
  
  belongs_to :organization
  belongs_to :user
  has_many :people, dependent: :destroy
  has_many :skills, dependent: :destroy
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.where( :user_id =>current_user.id)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id= current_user.id 
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description, :organization_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, :html => { :class => "form-horizontal group" } do |f| %>

  <div class="field">
    <%= f.label :organization %><br>
    <%= f.collection_select :organization_id, Organization.where( :user_id =>current_user.id), :id, :name,{},{:class => 'form-control'} %>
    <% if !(Organization.where( :user_id =>current_user.id)).exists? %>
    <p style="color:red;"><%= "Please create organiztion" %></p>
    <% end %>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <% if @group.errors.any? %>
    <% @group.errors.full_messages.each do |message| %>
        <% if message=~ /Name.*/ %>
        <p style="color:red;"><%= message %></p>
        <% end %>
    <% end %>
    <% end %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
  </div>
<br />
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            groups_path, :class => 'btn btn-default' %>

<% end %>

app/views/groups/edit.html.erb
<div style="width:30%;">
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/groups/index.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="table-responsive">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
<script>
$(function(){
  $(".btn1").css({'background':'#F8F8F8','box-shadow':'0px 0px 10px #d8d8d8','padding':'2px 4px','color':'#333'});$(".btn-danger").css({'color':'white'});
});
</script>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group_path(group), :class => 'btn btn1', :onmouseover => "$(this).css({'background':'#F8F8F8','box-shadow':'0px 0px 10px #666666','padding':'2px 4px','color':'#333'});", :onmouseleave => "$(this).css({'box-shadow':'0px 0px 10px #d8d8d8'});" %></td>
        <td><%= group.description %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_group_path(group), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      group_path(group),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_group_path,
            :class => 'btn btn-primary' %>

app/views/groups/new.html.erb
<div style="width:30%;">
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/groups/show.html.erb
<div style="width:50%;">
<%- model_class = Group -%>
<div class="page-header">
<div style="position:relative;margin-left:15%;">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @group.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @group.description %></dd>
  <dt><strong>Belongs to:</strong></dt>
  <dd><b>ORG :</b>&nbsp;<%= @group.organization.name %></dd>
  <dt><strong>People :</strong></dt>
  <dd><% @group.people.each do |person| %>
         <%= person.name %><br />
      <% end %>
  </dd>
</dl>
<div style="position:relative;margin-left:15%;">
<%= link_to t('.back', :default => t("helpers.links.back")),
              groups_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_group_path(@group), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              group_path(@group),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

</div>
</div>