config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :people

  resources :skills

  resources :groups

  resources :organizations

  resources :todos

  resources :comments
  
  root "organizations#home"
  
  post "/group_list" => "people#group_list"
  
  post "/skill_list" => "people#skill_list"
  
  post "/s_group_list" => "skills#s_group_list"

  get "/orgns" => "todos#orgns"

  get "/persn" => "todos#persn"

  get "/pple" => "todos#pple"

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :groups, dependent: :destroy
  belongs_to :user

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.where( :user_id =>current_user.id)
  end
  
  def home
    
  end
  
  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)
    @organization.user_id= current_user.id 
    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :city, :description)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for @organization, :html => { :class => "form-horizontal organization" } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <% if @organization.errors.any? %>
    <% @organization.errors.full_messages.each do |message| %>
        <% if message=~ /Name.*/ %>
        <p style="color:red;"><%= message %></p>
        <% end %>
    <% end %>
    <% end %>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
  </div>
  <br />
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            organizations_path, :class => 'btn btn-default' %>
<% end %>

app/views/organizations/edit.html.erb
<div style="width:30%;">
<%- model_class = Organization -%>
<div class="page-header">
<h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/organizations/home.html.erb
<div class="page-header">
  <h1>WELCOME TO DO SOME CRUD OPERATIONS</h1>
</div>

<%= link_to image_tag("home.jpg", :class => "img-responsive"), organizations_path, title: "Click here to view Organization" %>

app/views/organizations/index.html.erb
<%- model_class = Organization -%>
<div class="page-header">
<h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="table-responsive">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
<script>
$(function(){
  $(".btn1").css({'background':'#F8F8F8','box-shadow':'0px 0px 10px #d8d8d8','padding':'2px 4px','color':'#333'});
  $(".btn-danger").css({'color':'white'});
});
</script>
  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= link_to organization.name, organization_path(organization), :class => 'btn btn1', :onmouseover => "$(this).css({'background':'#F8F8F8','box-shadow':'0px 0px 10px #666666','padding':'2px 4px','color':'#333'});", :onmouseleave => "$(this).css({'box-shadow':'0px 0px 10px #d8d8d8'});" %></td>
        <td><%= organization.city %></td>
        <td><%= organization.description %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_organization_path(organization), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      organization_path(organization),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_organization_path,
            :class => 'btn btn-primary' %>

app/views/organizations/new.html.erb
<div style="width:30%;">
<%- model_class = Organization -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/organizations/show.html.erb
<div style="width:50%;">
<%- model_class = Organization -%>
<div class="page-header">
<div style="position:relative;margin-left:15%;">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @organization.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @organization.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @organization.description %></dd>
  <dt><strong>Groups:</strong></dt>
  <dd><% @organization.groups.each do |group| %>
         <%= group.name %><br />
      <% end %>
  </dd>
  <dt><strong>People:</strong></dt>
  <dd><table><% @organization.groups.each do |group| %>
         <% group.people.each do |person| %>
           <tr>
           <td><%= person.name %></td><td>(<b>GROUP :</b><%= "#{group.name})" %></td>
           </tr>
         <% end %>
      <% end %></table>
  </dd>
</dl>

<div style="position:relative;margin-left:15%;">
<%= link_to t('.back', :default => t("helpers.links.back")),
              organizations_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_organization_path(@organization), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              organization_path(@organization),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
</div>