config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :people

  resources :skills

  resources :groups

  resources :organizations

  resources :todos

  resources :comments
  
  root "organizations#home"
  
  post "/group_list" => "people#group_list"
  
  post "/skill_list" => "people#skill_list"
  
  post "/s_group_list" => "skills#s_group_list"

  get "/orgns" => "todos#orgns"

  get "/persn" => "todos#persn"

  get "/pple" => "todos#pple"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= favicon_link_tag 'logo.png'%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="width:100%;">

<% if user_signed_in? %>

<%= nav_bar :brand => image_tag('logo.png', style: "max-width:50px;max-height:40px;margin-top:-22%; " ), :responsive => true do %>
    <%= menu_group do %>
        <%= drop_down 'Organization' do %>
            <%= nav_link 'View Organization', organizations_path  %>
			<%= nav_link 'New Organization', new_organization_path %>
		<% end %>
		<%= drop_down 'Group' do %>
            <%= nav_link 'View Group', groups_path %>
			<%= nav_link 'New Group', new_group_path %>
		<% end %>
		<%= drop_down 'People' do %>
            <%= nav_link 'View People', people_path %>
			<%= nav_link 'New People', new_person_path %>
		<% end %>
		<%= drop_down 'Skill' do %>
            <%= nav_link 'View Skill', skills_path %>
			<%= nav_link 'New Skill', new_skill_path %>
		<% end %>
            <%= nav_link 'To-dos', todos_path %>
            <%= nav_link current_user.email, ""%>
         <% end %>   
    
<% end %>
<div style="width:100%;">
<%= link_to 'Logout', destroy_user_session_path, :method=>'delete', style: "float:right;color:black;box-shadow: 0px 0px 6px black;padding:0.1% 0.2%;margin-right:3%;margin-top:1%;", :class =>"btn btn-default" %>
</div><br />
<div style="width:83%;margin:0 auto;"><%= yield %></div>

<% else %>
<div style="width:100%;height:50px;background-color:#e8f2f4">
<%= link_to 'Sign_up', new_user_registration_path, style: "float:left;color:white;padding:0.1% 0.2%;margin-left:1%;margin-top:1%;", :class =>"btn btn-primary" %>
<%= link_to 'Login', new_user_session_path, style: "float:right;color:white;padding:0.1% 0.2%;margin-right:1%;margin-top:1%;", :class =>"btn btn-info" %>
</div>
<br />
<% if !notice.nil? %>
<p class="notice" style="width:100%;text-align:center;"><%= notice %></p>
<% end %>
<div class="container">
<div class="col-md-6"><%= link_to image_tag("home.jpg", :class => "img-responsive"), organizations_path, title: "Click here to view Organization" %></div>
<div class="col-md-6">
<%= yield %>

</div>
</div>
<% end %>

</body>
</html>